apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vihatoncom-ingress
  namespace: vihatoncom
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: vihaton.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vihatoncom-service
              servicePort: 3000
    - host: www.vihaton.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vihatoncom-service
              servicePort: 3000
    - host: vilihatonen.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vihatoncom-service
              servicePort: 3000
    - host: www.vilihatonen.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vihatoncom-service
              servicePort: 3000
  tls:
    - hosts:
        - www.vihaton.com
        - vihaton.com
        - www.vilihatonen.com
        - vilihatonen.com
      secretName: vihaton-tls
