service:
  type: LoadBalancer

  ## HTTP Port
  ##
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https

ghostProtocol: https
ghostHost: blog.vihaton.com
