apiVersion: v1
kind: Service
metadata:
  namespace: vihatoncom
  name: vihatoncom-service
spec:
  selector:
    app: vihatoncom
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
